apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fe
spec:
  selector:
    matchLabels:
      app: gcloudtest
      tier: fe
  replicas: 1
  template:
    metadata:
      labels:
        app: gcloudtest
        tier: fe
    spec:
      containers:
      - name: gcloudtest-fe
        image: gcr.io/deployment-test-239915/gcloud-test-fe:v12
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
